### ISSUE TITLE
Failed to create window: VersionUnavailable: GLX: Failed to create context: BadValue

### ISSUE THREAD

**Issue by Mg138** [Vencord/Installer#98]
Full log:

```
Downloading Installer...
X11 detected

Now running VencordInstaller
Do you want to run as root? [Y|n]
This is necessary if Discord is in a root owned location like /usr/share or /opt
> y
Running with sudo
VencordInstaller was run with root privileges, actual user is madeline
Looking up HOME of madeline
Actual HOME is /home/madeline
Using UserConfig
Checking if /home/madeline/.config/Vencord/dist exists: Yes
Is Dev Install:  false
Found existing Vencord Install. Checking for hash...
Fetching https://api.github.com/repos/Vendicated/Vencord/releases/latest
Existing hash is 1d77ab0
Checking if /opt/discord/resources exists: Yes
Checking if /opt/discord/resources/app exists: No
Checking if /opt/discord/resources/app.asar is directory: Yes
Found Discord install at  /opt/discord
Checking for Installer Updates...
Fetching https://api.github.com/repos/Vencord/Installer/releases/latest
Finished fetching GitHub Data
Latest hash is c752be4 Local Install is outdated!
panic: failed to create window: VersionUnavailable: GLX: Failed to create context: BadValue (integer parameter out of range for operation)

goroutine 1 [running, locked to thread]:
github.com/AllenDang/giu.NewMasterWindow({0xa4528d, 0x11}, 0x4b0, 0x320, 0xa0?)
        /home/runner/go/pkg/mod/github.com/!allen!dang/giu@v0.6.2/MasterWindow.go:68 +0x41f
main.main()
        /home/runner/work/Installer/Installer/gui.go:70 +0x98

```

**Comment by Vendicated** [comment]
install mesa or some other opengl impl or use the cli

**Comment by Mg138** [comment]
Mesa is installed.

**Comment by Mg138** [comment]
Nevermind, it's nvidia graphics driver updating shenanigans.
